# Irrigation Machine
## Multi-label classification

![image](https://goodboychan.github.io/chans_jupyter/images/copied_from_nb/image/multi_label.png)

## An irrigation machine

We're going to automate the watering of farm parcels by making an intelligent irrigation machine. Multi-label classification problems differ from multi-class problems in that each observation can be labeled with zero or more classes. So classes/labels are not mutually exclusive, you could water all, none or any combination of farm parcels based on the inputs.

![image2](https://goodboychan.github.io/chans_jupyter/images/copied_from_nb/image/mutilabel_dataset.jpg)

In [1]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
# Instantiate a Sequential model
model = Sequential()

In [3]:
# Add a hidden layer of 64 neurons and a 20 neuron's input
model.add(Dense(64, input_shape=(20,), activation='relu'))

# Add an output layer of 3 neurons with sigmoid activation
model.add(Dense(3, activation='sigmoid'))

# Compile your model with binary crossentropy loss
model.compile(optimizer='adam',
           loss = 'binary_crossentropy',
           metrics=['accuracy'])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                1344      
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 195       
Total params: 1,539
Trainable params: 1,539
Non-trainable params: 0
_________________________________________________________________


In [5]:
irrigation = pd.read_csv('irrigation_machine.csv', index_col=0)

In [6]:
parcels = irrigation[['parcel_0', 'parcel_1', 'parcel_2']].to_numpy()
sensors = irrigation.drop(['parcel_0', 'parcel_1', 'parcel_2'], axis=1).to_numpy()

In [7]:
sensors_train, sensors_test, parcels_train, parcels_test = train_test_split(sensors, parcels, test_size=0.3, stratify=parcels)

In [8]:
# Train for 100 epochs using a validation split of 0.2
model.fit(sensors_train, parcels_train, epochs = 100, validation_split = 0.2)

Epoch 1/100
35/35 [==============================] - 1s 21ms/step - loss: 0.8825 - accuracy: 0.3920 - val_loss: 0.5956 - val_accuracy: 0.4036
Epoch 2/100
35/35 [==============================] - 0s 7ms/step - loss: 0.5108 - accuracy: 0.5107 - val_loss: 0.4728 - val_accuracy: 0.5643
Epoch 3/100
35/35 [==============================] - 0s 9ms/step - loss: 0.4177 - accuracy: 0.5839 - val_loss: 0.4085 - val_accuracy: 0.5429
Epoch 4/100
35/35 [==============================] - 0s 8ms/step - loss: 0.3679 - accuracy: 0.5911 - val_loss: 0.3699 - val_accuracy: 0.6214
Epoch 5/100
35/35 [==============================] - 0s 6ms/step - loss: 0.3351 - accuracy: 0.6018 - val_loss: 0.3460 - val_accuracy: 0.5250
Epoch 6/100
35/35 [==============================] - 0s 8ms/step - loss: 0.3119 - accuracy: 0.5973 - val_loss: 0.3314 - val_accuracy: 0.6107
Epoch 7/100
35/35 [==============================] - 0s 9ms/step - loss: 0.2958 - accuracy: 0.6062 - val_loss: 0.3151 - val_accuracy: 0.5714
Epoch 8/100


In [9]:
# Predict on sensors_test and round up the predictions
preds = model.predict(sensors_test)
preds_rounded = np.round(preds)

In [10]:
# Print rounded preds
print('Rounded Predictions: \n', preds_rounded)

Rounded Predictions: 
 [[1. 1. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [11]:
# Evaluate your model's accuracy on the test data
accuracy = model.evaluate(sensors_test, parcels_test)[1]

19/19 [==============================] - 0s 5ms/step - loss: 0.2958 - accuracy: 0.5817
